/** Canonical site URL and social share images. */
export const SITE_URL = "https://bigfivegroup.africa";

export const SITE_NAME = "Big Five Group Africa";

/**
 * Default Open Graph card (home hero + bigfivegroup-logo.png only — no plate).
 * Prefer ogImageFor(slug) on pillar pages so the shared page uses that pillar’s hero.
 */
export const SITE_OG_IMAGE = {
  url: "/og/home.jpg",
  width: 1200,
  height: 630,
  alt: "Big Five Group Africa",
  type: "image/jpeg",
} as const;

/** Map route segment → prebuilt OG asset under /og/{slug}.jpg */
const OG_SLUGS = new Set([
  "home",
  "group",
  "agri",
  "foods",
  "direct",
  "access",
  "connect",
  "impact",
  "leadership",
  "foundation",
  "global",
  "africa",
  "royal",
  "about",
  "contact",
  "newsletter",
  "brand",
  "methodology",
  "partner-kit",
  "updates",
]);

/**
 * Social share image for a page: that page’s hero + bigfivegroup-logo.png only.
 * Generated by: node scripts/generate-og-images.mjs
 */
export function ogImageFor(slug: string): {
  url: string;
  width: number;
  height: number;
  alt: string;
  type: string;
} {
  const key = OG_SLUGS.has(slug) ? slug : "home";
  return {
    url: `/og/${key}.jpg`,
    width: 1200,
    height: 630,
    alt: `Big Five Group Africa — ${key}`,
    type: "image/jpeg",
  };
}

/** Spread into page metadata openGraph + twitter.images */
export function siteSocialImages(slug = "home"): {
  openGraph: { images: [ReturnType<typeof ogImageFor>] };
  twitter: { card: "summary_large_image"; images: [string] };
} {
  const img = ogImageFor(slug);
  return {
    openGraph: { images: [img] },
    twitter: {
      card: "summary_large_image",
      images: [img.url],
    },
  };
}
